import os
import cv2

YOLO_GENERAL_MODEL_PATH = "models/yolov8n.pt"
YOLO_POSE_MODEL_PATH = "models/yolov8s-pose.pt"

CLASS_NAMES = {
    0: 'person',
    1: 'bicycle',
    2: 'car',
    3: 'motorcycle',
    5: 'bus',
    7: 'truck',
}

PERSON_CLASS_ID = 0
VEHICLE_CLASS_IDS = [2, 5, 7]
BIKE_CLASS_IDS = [1, 3]

FORBIDDEN_ZONE_COOLDOWN_SECONDS = 5
VIOLATION_IMAGE_SAVE_DIR = "violations"
if not os.path.exists(VIOLATION_IMAGE_SAVE_DIR):
    os.makedirs(VIOLATION_IMAGE_SAVE_DIR)

VANDALISM_DIST_THRESH = 100
VANDALISM_MOTION_THRESH = 1500
VANDALISM_TRACKER_MAX_AGE = 30 

STOP_DURATION_SECONDS = 3
PERSON_PROXIMITY_THRESHOLD_PIXELS = 100
PERSON_GRACE_PERIOD_SECONDS = 3.0

ENTRY_DIRECTION_SAMPLES = 30 # Increased to 30 frames for smoother direction detection
ENTRY_X_DECREASING_THRESHOLD = 20 
ENTRY_MAX_TRACK_INACTIVE_SECONDS = 5 # Specific to entry detector

GENERAL_TRACK_INACTIVE_SECONDS = 5.0 # General constant for tracker cleanup

HUMAN_FIGHT_DETECTION_THRESHOLD = 5
HUMAN_FIGHT_HISTORY_SIZE = 20
HUMAN_FIGHT_ALERT_COOLDOWN = 5
HUMAN_VELOCITY_THRESHOLD_FIGHT = 0.04

HUMAN_FALL_HEAD_TO_HIP_Y_RATIO = 0.55
HUMAN_FALL_BODY_ALIGNMENT_X_DEVIATION = 0.25
HUMAN_FALL_VERTICAL_DROP_RATIO = 0.08
HUMAN_FALL_DETECTION_HISTORY_FRAMES = 15
HUMAN_FALL_STILLNESS_THRESHOLD = 0.02
HUMAN_MIN_FALL_INDICATORS = 2

DISPLAY_WINDOW_NAME_PREFIX = "Surveillance Feed"
ANNOTATION_COLOR_VIOLATION = (0, 0, 255)
ANNOTATION_COLOR_WARNING = (0, 165, 255)
ANNOTATION_COLOR_NORMAL = (0, 255, 0)
ANNOTATION_COLOR_ZONE_BOUNDARY = (255, 255, 0)
ANNOTATION_COLOR_ZONE_FILL = (255, 0, 0)

FONT = cv2.FONT_HERSHEY_SIMPLEX
FONT_SCALE = 0.7
FONT_THICKNESS = 2
TEXT_OFFSET_Y = 10

NOSE = 0
LEFT_EYE = 1
RIGHT_EYE = 2
LEFT_EAR = 3
RIGHT_EAR = 4
LEFT_SHOULDER = 5
RIGHT_SHOULDER = 6
LEFT_ELBOW = 7
RIGHT_ELBOW = 8
LEFT_WRIST = 9
RIGHT_WRIST = 10
LEFT_HIP = 11
RIGHT_HIP = 12
LEFT_KNEE = 13
RIGHT_KNEE = 14
LEFT_ANKLE = 15
RIGHT_ANKLE = 16
CONF_THRESHOLD = 0.5